bezlio/bezlio-apps

README.md

Links in the readme were pointing to recipes. Pointed them to apps.

Readme links fix

---

roles/sales-rep/invoice-inquiry/js/onDataChange.js

Fixed bug where .touppercase would throw an error on sorting nulls.

Fixed Sorting Bug

---

roles/sales-rep/accounts-view/js/onDataChange.js

Fixes #31 . Used a split, to truncate the date value.

Truncate date at T to get correct date.

---

roles/sales-rep/invoice-inquiry/js/onDataChange.js
roles/sales-rep/order-inquiry/js/onDataChange.js

Closes #74 . The currency pipe doesn't like a "" value. Fixed in other bezls as well

Invalid arg for pipe

---

libraries/epicor/crm.js

Add multi-new row support to tasks.

---

roles/sales-rep/accounts-view/js/onDataChange.js
roles/sales-rep/accounts-view/js/onStartup.js
roles/sales-rep/accounts-view/sql/Epicor10/GetAccounts.sql
roles/sales-rep/tasks-view/js/onDataChange.js

Sales rep - tasks view - push updated due date (refactor) #27

---

roles/sales-rep/trip-planner/sql/Prophet21/trip-planner/CreateGeocodeLocationTable.sql
roles/sales-rep/trip-planner/sql/Prophet21/trip-planner/GetCustomersWithAddress.sql
roles/sales-rep/trip-planner/sql/Prophet21/trip-planner/SetGeocodeOnAddress.sql

Blind SQL conversion.

---

roles/sales-rep/map-view/BezlExport.txt
roles/sales-rep/map-view/js/customer.js
roles/sales-rep/map-view/js/map.js
roles/sales-rep/map-view/js/onDataChange.js
roles/sales-rep/map-view/js/onStartup.js

Fixed some bugs with Mapview. Changed query location on dev-epicor10, made changes to query calls. Added jsGrid, and a refresh of that grid after distances are calculated

Mapview Updated

---

roles/sales-rep/crm-calls-view/js/onStartup.js
roles/sales-rep/crm-calls-view/sql/Epicor10/GetAccountsCallHistory.sql

Add back the EmailAddress parameter to the GetAccountsCallHistory query.

---

roles/sales-rep/invoice-inquiry/sql/Visual8/InvoiceInquiry.sql
roles/sales-rep/order-inquiry/sql/Visual8/OrderInquiry.sql

Added OrderInquiry.sql and InvoiceInquiry.sql to new Visual8 folders

Visual8 SQL Files

---

roles/sales-rep/order-inquiry/sql/Visual8/OrderInquiry.sql
roles/sales-rep/trip-planner/sql/Visual8/GetCustomersWithAddress.sql
roles/sales-rep/trip-planner/sql/Visual8/SetGeocodeOnAddress.sql

Updated the date format to resolve UTC issue, OrderInquiry.sql
Added queries to \trip-planner\sql\Visual8

Visual8 query updated

---

roles/sales-rep/accounts-view/BezlExport.txt
roles/sales-rep/accounts-view/js/account.js
roles/sales-rep/accounts-view/js/onDataChange.js
roles/sales-rep/accounts-view/js/onStartup.js

Sales rep   accounts view   data disappears due to data cache #151

---

roles/sales-rep/invoice-inquiry/js/onStartup.js
roles/sales-rep/order-inquiry/js/onStartup.js
roles/sales-rep/rma-inquiry/js/onStartup.js

Closes #152 , sets the default dates for the last 30 days. This is for Invoice Inquiry, Order Inquiry, and RMA Inquiry.

30 day range

---

roles/edi/edi850I/js/edi850I.js
roles/edi/edi850I/js/onStartup.js

Made a few changes to fix filtering and searching after adding sorting buttons to grid.

Fixed code to handle new table <div> rows.

---

roles/sales-rep/accounts-view/BezlExport.txt

@aellis , pulled down accounts view on dev, it was throwing errors because it was pointing to a deleted branch.  I just pointed the urls to azure dev.

Changed URLs to point to azure dev

---

roles/sales-rep/tasks-view/sql/Epicor10/GetAccountsTasks.sql

Comment out WHERE clause that limits tasks to currently logged in user.

---

roles/sales-rep/accounts-view/js/account.js
roles/sales-rep/accounts-view/js/onDataChange.js

Sales rep - accounts view - sorts not preserved on refresh #166

---

roles/sales-rep/crm-calls-view/js/account.js

Sales rep - crm history - new entries disappear shortly after being added #129

---

roles/sales-rep/accounts-view/js/account.js
roles/sales-rep/accounts-view/js/onStartup.js
roles/sales-rep/attachments-view/js/onStartup.js
roles/sales-rep/crm-calls-view/js/onStartup.js
roles/sales-rep/customer-price-list/js/priceList.js
roles/sales-rep/invoice-inquiry/js/invoice.js
roles/sales-rep/order-inquiry/js/order.js
roles/sales-rep/rma-inquiry/js/rma.js
roles/sales-rep/tasks-view/js/onDataChange.js
roles/sales-rep/tasks-view/js/onStartup.js

Changed all existing references to .panel to #bezlpanel

---

roles/edi/edi850I/js/edi850I.js
roles/edi/edi850I/js/onStartup.js

Pulling this because the differences in code keep crashing my Google Chrome. Approval still needs to be done. Will create a new branch for that.

Edi approve delete

---

roles/sales-rep/accounts-view/sql/Prophet21/GetAccounts.sql
roles/sales-rep/accounts-view/sql/Prophet21/GetAccountsAttachments.sql
roles/sales-rep/accounts-view/sql/Prophet21/GetAccountsCallHistory.sql
roles/sales-rep/accounts-view/sql/Prophet21/GetAccountsContacts.sql
roles/sales-rep/accounts-view/sql/Prophet21/GetAccountsTasks.sql

Accounts View - Prophet 21 SQL

---

roles/sales-rep/map-view/sql/Prophet21/GetCRMCallHistory.sql
roles/sales-rep/map-view/sql/Prophet21/GetCallTypes.sql
roles/sales-rep/map-view/sql/Prophet21/GetCustomerAttachments.sql
roles/sales-rep/map-view/sql/Prophet21/GetCustomersWithAddress.sql
roles/sales-rep/map-view/sql/Prophet21/GetInvoiceHistory.sql
roles/sales-rep/map-view/sql/Prophet21/GetOpenTasks.sql
roles/sales-rep/map-view/sql/Prophet21/OpenQuotes.sql
roles/sales-rep/map-view/sql/Prophet21/SetGeocodeOnAddress.sql
roles/sales-rep/trip-planner/sql/Prophet21/trip-planner/GetCustomersWithAddress.sql
roles/sales-rep/trip-planner/sql/Prophet21/trip-planner/SetGeocodeOnAddress.sql

Map View - Prophet 21 SQL

---

roles/common/geolocation/js/customer.js
roles/common/geolocation/js/map.js
roles/common/geolocation/js/onDataChange.js
roles/sales-rep/map-view/js/customer.js
roles/sales-rep/map-view/js/map.js
roles/sales-rep/map-view/js/onStartup.js
roles/sales-rep/trip-planner/BezlExport.txt
roles/sales-rep/trip-planner/js/customer.js
roles/sales-rep/trip-planner/js/map.js
roles/sales-rep/trip-planner/js/onStartup.js

Fixes #233 . Seth pointed out there was a circular dependency between the map file and the customer file.  This was causing the map file to not be loaded, which in turned caused it to be undefined when calling its functions from the customer file.   There are a couple ways of handling circular dependencies; Seth provided this link; http://www.bitnative.com/2015/02/03/circular-dependencies-in-requirejs/
I went about it a different way, and just set a bezl.var to each file in the onStartup function, then used that var to reference the files in all the js files.  This can be adjusted if we decide this is not the best way.  
Fixed same issues in map-view and geocoder.
Trip planner bezlExport was pointed to the branch, will just require removal of one line to return it back to dev.

Undefined error trip planner

---

roles/common/geolocation/BezlExport.txt

Updated the geocoder cdn urls. was pointing at rawgit, where it would 404. Now points to bezlio-apps-dev or prod

Updated the geocoder

---

roles/sales-rep/README.md

The readme had a broken link for the main-view sql file, just replaced it with a list of links, corresponding with the different bezls
Closes #247

Updated Readme, broken link

---

roles/edi/edi850I/js/edi850I.js

Now uses user login to find if user has right to approve/delete/view/save.

Wrapped up user rights in approving/deleting/viewing/saving.

---

roles/edi/edi850I/js/edi850I.js

I need this pulled so my functions work in testing.

Added SelectAll/SelectNone function.

---

roles/sales-rep/accounts-view/BezlExport.txt

Added innerHTML for Customer Notes.

---

roles/sales-rep/README.md
roles/sales-rep/accounts-view/README.md
roles/sales-rep/attachments-view/README.md
roles/sales-rep/crm-calls-view/README.md
roles/sales-rep/customer-price-list/README.md
roles/sales-rep/invoice-inquiry/README.md
roles/sales-rep/map-view/README.md
roles/sales-rep/order-inquiry/README.md
roles/sales-rep/rma-inquiry/README.md
roles/sales-rep/tasks-view/README.md
roles/sales-rep/trip-planner/README.md

Closes #247. Closes #65. Closes #66. Closes #67. Closes #68. Closes #69. Closes #70. Closes #71. Closes #72. Closes #73.

Sales rep readme.md needs revised #247

---

roles/sales-rep/accounts-view/sql/Visual8/GetAccounts.sql

Version was way behind, and required a number of additional fields including AR aging

Updated VISUAL SQL for GetAccounts

---

roles/sales-rep/order-inquiry/sql/Visual8/GetAccounts.sql

Brought it current with all related fields

Updated GetAllAccounts for Order Inquiry

---

roles/sales-rep/invoice-inquiry/sql/Visual8/GetAccounts.sql

Wonder if there's a way to have only one "GetAllAccounts.sql" file in GitHub, since there will only ever be one version in sales-rep-queries on the server?  The same file supports Accounts View, Order Inquiry, and Invoice Inquiry...right??

Update GetAllAccounts for Invoice Inquiry

---

structure.json

Adding the geocoder to the apps page.

Updated structure.json for geocoder

---

roles/edi/edi855O/js/edi855O.js

I completed 855. Moving onto 856.

Completed 855.

---

roles/sales-rep/trip-planner/js/customer.js
roles/sales-rep/trip-planner/versions/1.0/js/customer.js
roles/sales-rep/trip-planner/versions/1.1/js/customer.js

Closes #325 . It was testing the key with ===, not ==. Which was causing no customers to be found with the key. Always just changed the name of some variables.

Fixed broken add to route btn, trip planner

---

roles/production-team-leader/main-view/js/onDataChange.js
roles/production-team-leader/main-view/versions/1.4/js/onDataChange.js

Fixed toUpper method call to toUpperCase.

toUpper => toUpperCase

---

roles/edi/edi810O/js/edi810O.js
roles/edi/edi810O/js/onStartup.js
roles/edi/edi850I/js/edi850I.js
roles/edi/edi850I/js/onStartup.js
roles/edi/edi855O/js/edi855O.js
roles/edi/edi855O/js/onStartup.js
roles/edi/edi856O/js/edi856O.js
roles/edi/edi856O/js/onStartup.js

now approval results are returned as they complete.

Completed asynchronous approval results.

---

roles/edi/edi810O/js/edi810O.js
roles/edi/edi850I/js/edi850I.js
roles/edi/edi855O/js/edi855O.js
roles/edi/edi856O/js/edi856O.js

Now able to define what SQL connection name you want to point to. This allows for multiple SQL connections.

Completed SQL Connection name variable 

---

roles/sales-rep/customer-price-list/BezlExport.txt
roles/sales-rep/customer-price-list/versions/CHANGELOG.md
roles/sales-rep/invoice-inquiry/BezlExport.txt
roles/sales-rep/invoice-inquiry/versions/CHANGELOG.md
roles/sales-rep/order-inquiry/BezlExport.txt
roles/sales-rep/order-inquiry/versions/CHANGELOG.md
roles/sales-rep/rma-inquiry/BezlExport.txt
roles/sales-rep/rma-inquiry/versions/CHANGELOG.md

Added more information to the drop down displays, request by customer.

Added drop down display changes

---

roles/edi/edi810O/BezlExport.txt
roles/edi/edi810O/js/edi810O.js
roles/edi/edi810O/versions/3.4.4/js/edi810O.js
roles/edi/edi830I/BezlExport.txt
roles/edi/edi830I/js/edi830I.js
roles/edi/edi830I/versions/3.4.4/js/edi830I.js
roles/edi/edi846O/BezlExport.txt
roles/edi/edi846O/js/edi846O.js
roles/edi/edi846O/versions/3.4.4/js/edi846O.js
roles/edi/edi850I/BezlExport.txt
roles/edi/edi850I/js/edi850I.js
roles/edi/edi850I/versions/3.4.4/js/edi850I.js
roles/edi/edi855O/BezlExport.txt
roles/edi/edi855O/js/edi855O.js
roles/edi/edi855O/versions/3.4.4/js/edi855O.js
roles/edi/edi856O/BezlExport.txt
roles/edi/edi856O/js/edi856O.js
roles/edi/edi856O/versions/3.4.4/js/edi856O.js
roles/edi/edi862I/BezlExport.txt
roles/edi/edi862I/js/edi862I.js
roles/edi/edi862I/versions/3.4.4/js/edi862I.js
roles/edi/edi940O/BezlExport.txt
roles/edi/edi940O/js/edi940O.js
roles/edi/edi940O/versions/3.4.4/js/edi940O.js
roles/edi/edi945I/BezlExport.txt
roles/edi/edi945I/js/edi945I.js
roles/edi/edi945I/versions/3.4.4/js/edi945I.js

Fixed up re-validating and deleting. Confirmed they work as anticipated.

Added document direction to revalidate.

---

roles/sales-rep/order-inquiry/BezlExport.txt
roles/sales-rep/order-inquiry/versions/1.2/BezlExport.txt

Hot Fix. In production the order inquiry bezl will point to the rma.js which it cannot find and throw an error. Change it to point to order.js

HOT FIX: Point Order inquiry to order.js

---

roles/edi/edi850I/js/edi850I.js

Need this pulled so I may test on my phone.

Edi mobile functionality  850

---

roles/sales-rep/tasks-view/js/task.js
roles/sales-rep/tasks-view/versions/1.0/js/task.js
roles/sales-rep/tasks-view/versions/1.1/js/task.js

Tasks array was empty before trying to update/push new tasks. Fixed in base, 1.0 and 1.1.

Epicor task view cannot add

---

libraries/epicor/crm.js
libraries/versions/1.4/epicor/crm.js
roles/sales-rep/tasks-view/BezlExport.txt
roles/sales-rep/tasks-view/js/onDataChange.js
roles/sales-rep/tasks-view/sql/Epicor10/GetAccountsTasks.sql
roles/sales-rep/tasks-view/sql/Epicor905/GetAccountsTasks.sql
roles/sales-rep/tasks-view/versions/1.2/BezlExport.txt
roles/sales-rep/tasks-view/versions/1.2/js/onDataChange.js
roles/sales-rep/tasks-view/versions/1.2/js/task.js
roles/sales-rep/tasks-view/versions/1.2/sql/Epicor10/GetAccountsTasks.sql
roles/sales-rep/tasks-view/versions/1.2/sql/Epicor905/GetAccountsTasks.sql

Modifications to version 1.2 requested by Sunlight.

Task view updates rev2

---

roles/sales-rep/accounts-view/js/account.js
roles/sales-rep/accounts-view/versions/CHANGELOG.md

Closes #403 . Added account contacts data query back in.  fixes a bug we were seeing where the contacts where not being pulled in.

Added AccountsContacts data call back.

---

libraries/epicor/quote.js
roles/sales-rep/quote-entry/js/onDataChange.js
roles/sales-rep/quote-entry/js/onStartup.js
roles/sales-rep/quote-entry/js/quote.js

Minor updates to allow Kaufman to use the Sales Tool bezl off of dev.

Sales rfq updating require

---

roles/customer-portal/order-entry/js/onDataChange.js

Fix for MKDiamond. 
Added a click function, and included a to uppercase.
Can we push this to live ?

Mk diamond bug fix

---

roles/edi/edi945I/js/edi945I.js

Corrected approval results to properly display in Bezlio.

Found an issue with 945. Corrected approval results.

---

roles/edi/edi945I/versions/4.0.3/js/edi945I.js

Forgot to add code to 4.0.3. Added to 4.0.3.

Added 945 changes to the version 4.0.3.

---

roles/edi/edi830I/BezlExport.txt
roles/edi/edi850I/js/edi850I.js
roles/edi/edi850I/versions/4.0.8/js/edi850I.js

Minor fix for 850's. Please leave branch open after pulling.

Minor fix for deleting 850's.
